#!/usr/bin/env bash

# vim

mkdir -p ~/dotfiles/vim/vim
ln -nfs ~/dotfiles/vim/vim ~/.vim
ln -nfs ~/dotfiles/vim/vimrc ~/.vimrc

# zsh
git clone https://github.com/robbyrussell/oh-my-zsh.git ~/dotfiles/zsh/oh-my-zsh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/dotfiles/zsh/custom/plugins/zsh-syntax-highlighting
ln -nfs ~/dotfiles/zsh/zshrc ~/.zshrc
ln -nfs ~/dotfiles/zsh/oh-my-zsh ~/.oh-my-zsh

# git
ln -nfs ~/dotfiles/git/gitignore_global ~/.gitignore_global
ln -nfs ~/dotfiles/git/gitconfig ~/.gitconfig

# tmux
ln -nfs ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
